<a href="https://colab.research.google.com/github/AkshayK25/GoOgle-ColAbOratories/blob/master/Numpy_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
n = int(input())
def tiling(n):
    result = np.zeros((n, n), dtype = int)
    result[::2, 1::2] = 1
    result[1::2, ::2] = 1
    return result
  
print(tiling(n))

4
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


**2D Array**

Description

From a 2D array extract all the rows of the 2 column.
Hint: 2 column will have index value as 1.

Execution Time Limit

5 seconds

In [0]:
import numpy as np
array_2d =np.array(input_list) 
input_list = [[5,6,7],[7,6,5],[0,8,7]]
new_arr = [x[1] for x in array_2d ]
print(np.array(new_arr))

[6 6 8]


In [0]:
import numpy as np
n = 4
arr = ([0,1])
print(np.tile(arr,(n,n//2)))

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


**Border Rows and Columns**

Description

Extract all the border rows and columns from a 2-D array.

Format:

Input: A 2-D Python list

Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:

Input 1:

[[11 12 13 14]

 [21 22 23 24]
 
 [31 32 33 34]]
 
Output 1:

[11 21 31]

[11 12 13 14]

[14 24 34]

[31 32 33 34]

Execution Time Limit
5 seconds

In [0]:
import numpy as np

input_list = [[11, 12, 13, 14],
 [21 ,22, 23, 24],
 [31, 32 ,33, 34]]

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
row_first = array_2d[0:1,:]
col_first = array_2d[:,0:1]
col_last = array_2d[:,3:4]
row_last = array_2d[2:4,:]
colnew = col_first.reshape(k)
print(colnew[0])
print(row_first[0])
coll = col_last.reshape(m)
print(coll[0])
print(row_last[0])


[11]
[11 12 13 14]
[14]
[31 32 33 34]
(3, 1) (3, 1)


In [0]:
import numpy as np
array_1= np.array([1, 2 ,3 ,5 ,4, 6 ,7 ,8, 5, 3, 2])
print(array_1[0::2])

[1 3 4 7 5 2]


In [0]:
import numpy as np

input_list = [[[1, 2], [5, 6]], [[3, 4], [7, 8]], [[9, 10, 11, 12]]]
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

# Import NumPy
import numpy as np
hos1 = np.vstack(list_1)
hos2 = np.vstack(list_2)
result = np.hstack([hos1,hos2])
vs = np.vstack(list_3)
vert = np.vstack([result,vs])
print(vert)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Stack Three Arrays**

Description

Horizontally stack two arrays using hstack, and finally, vertically stack the resultant array with the third array. 

Example:

Input 1:

[[1, 2],

 [5, 6]]

[[3, 4],

 [7, 8]]

[[9, 10, 11, 12]]

Output 1:

[[1 2 3 4]

 [5 6 7 8]
 
 [9 10 11 12]]

**Linear algebra**

Description

Find the inverse, eigenvalues, eigenvectors, determinants of a given matrix 'array_1'.

In [0]:
input_list = [[1,2,3],[2,3,4],[4,2,6]]

list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]

import numpy as np
array_1 = np.array([list_1,list_2,list_3])
eigen = np.linalg.eig(array_1)
inv = np.linalg.inv(array_1)
det = np.linalg.det(array_1)
print(eigen)
print(inv)
print(det)

(array([ 9.62347538, -0.62347538,  1.        ]), array([[-0.38508979, -0.82767094, -0.26726124],
       [-0.55951021, -0.14241368, -0.80178373],
       [-0.73393063,  0.54284358,  0.53452248]]))
[[-1.66666667  1.          0.16666667]
 [-0.66666667  1.         -0.33333333]
 [ 1.33333333 -1.          0.16666667]]
-6.0


In [0]:
def sqn():
  return [i**2 for i in range(1, 5)]
      
import numpy as np   
arr = np.tile(sqn(),(4,1))
print(arr)

[[ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]]


**3D NumPy Array**

Description

Create a 3D array containing the first 45 natural numbers such that the numbers are divided in 3 blocks, 5 rows and 3 columns.

Input: 

There is no input.

Output:

[ [ [ 0  1  2]

  [ 3  4  5]
  
  [ 6  7  8]
  
  [ 9 10 11]
  
  [12 13 14]]

[[15 16 17]

  [18 19 20]
  
  [21 22 23]
  
  [24 25 26]
  
  [27 28 29]]

[[30 31 32]

  [33 34 35]
  
  [36 37 38]
  
  [39 40 41]
  
  [42 43 44] ] ]

In [0]:
import numpy as np

arr1 = np.arange(0,15,1,dtype = int)
arr2 = np.arange(15,30,1,dtype = int)
arr3 = np.arange(30,45,1,dtype = int)

fnarr1 =arr1.reshape(5,3)
fnarr2 =arr2.reshape(5,3)
fnarr3 =arr3.reshape(5,3)

print(np.array([fnarr1,fnarr2,fnarr3]))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]


**Linspace Function**

Description

Create an array containing 15 numbers. The array should start from the number 21 and end in number 25. The array should have evenly spaced numbers between 21 and 25 in increasing order.

Input: No input

Output: 

[21.   21.28571429     21.57142857   21.85714286   
22.14285714   22.42857143  22.71428571  23.   23.28571429  
23.57142857   23.85714286   24.14285714
24.42857143   24.71428571 25.]


In [0]:
import numpy as np

arr = np.linspace(21, 25 ,15)
print(arr)

[21.         21.28571429 21.57142857 21.85714286 22.14285714 22.42857143
 22.71428571 23.         23.28571429 23.57142857 23.85714286 24.14285714
 24.42857143 24.71428571 25.        ]


**Vectorize Function**

Description

Using the vectorize() function, apply a quadratic function, x2  - 5x + 1 only on the last row of the array 

[[1,2,3,4],

[4,7,5,6], 

[9,0,7,8],

[6,7,8,5]]. 

Input:

[ [1,2,3,4],

[4,7,5,6],

[9,0,7,8],

[6,7,8,5] ]

Output:

[ 7 15 25  1]

In [0]:
input_list = [[1,2,3,4], [4,7,5,6], [9,0,7,8], [6,7,8,5]]

num_list_1 = input_list[0]
num_list_2 = input_list[1]
num_list_3 = input_list[2]
num_list_4 = input_list[3]

import numpy as np
def quad(x):
    eq = (x**2) -5*x +1
    return eq
    
print(quad(np.array(num_list_4)))

[ 7 15 25  1]


In [0]:
import numpy as np

list1 = [[1, 2, 3, 4], [11, 12, 13, 14]] 
list2 = [[-5, -6], [-7, -8], [15, 16], [17, 18]]

arr1 = np.array(list1)
arr2 = np.array(list2)
result = np.dot(list1,list2)
print(result)

[[ 94  98]
 [294 298]]


In [0]:

import numpy as np
arr = np.full((11,12),5,dtype = int)
k = np.where(arr == 100)
print(k)

(array([], dtype=int64), array([], dtype=int64))


**Swap two rows**

Description

Given m and n, swap the mth and nth rows of the 2-D NumPy array given below.


a = 
           
         [ [4 3 1] 

         [5 7 0] 
         
         [9 9 3] 
         
         [8 2 4]] 

Example: 

Input 1: 

0 
2 

Output 1: 

[[9 9 3] 

 [5 7 0]
 
 [4 3 1] 
 
 [8 2 4]]

In [0]:

import numpy as np

a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
m = int(input())
n = int(input())

# Write your code for swapping here
a[[m,n]] = a[[n,m]]
print(a)

0
2
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [0]:

n = int(input())

import numpy as np

# Create an 'n*n' array of all ones
border_array = np.ones((n, n), dtype = int)

# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices
border_array[1:-1, 1:-1] = 0

# Print the array created
print(border_array)

5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Create border array**

Description

Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside. 

Note: Make sure the array is of type int.

Example: 

Input 1: 

4 

Output 1: 

[[1 1 1 1] 

[1 0 0 1]

[1 0 0 1]

[1 1 1 1]]

Input 2: 

2 
Output 2: 

[[1 1] 

 [1 1]] 