<a href="https://colab.research.google.com/github/AkshayK25/GoOgle-ColAbOratories/blob/master/PandAs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
pd.set_option('display.max_rows',517)
pd.set_option('display.max_columns',33)
pd.options.display.show_dimensions = False
print(df.describe())
print(df.columns)
print(df.shape)

                X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663   
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477   
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000   
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000   
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000   
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000   
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000   

             temp          RH        wind        rain         area  
count  517.000000  517.000000  517.000000  517.000000   517.000000  
mean    18.889168   44.288201    4.017602    0.021663    12.847292  
std      5.806625   16.317469    1.791653    0.295959    63.655

**Pandas Series**

Description

Create a series using list = [6,7,8,9,2,3,4,5] and print the output series as the square of each number in the list.

Hint: If input series = 1,2,3 the output series should be 1,4,9
Hint: First create the series and then using apply and lambda find the output series.

In [0]:
import numpy as np
import pandas as pd
lists = [6,7,8,9,2,3,4,5]
def sq():
    new = []
    for x in lists:
        new.append(x**2)
    return new

flist = sq()
series_1 = pd.Series(lists)
series_2 = pd.Series(flist)
print(series_1)
print(series_2)

0    6
1    7
2    8
3    9
4    2
5    3
6    4
7    5
dtype: int64
0    36
1    49
2    64
3    81
4     4
5     9
6    16
7    25
dtype: int64


**Manual Indexing**

Description

Create a panda series that contains the first ‘n’ natural numbers and their respective squares. The first ‘n’ numbers should appear in the index position. 
Hint: Use manual indexing.
 
Format:
Input: A natural number 'n'
Output: A pandas series with the first 'n' natural numbers in the index position and their respective squares in the adjacent column.


In [0]:
n = int(input())
lists = []
def create_list(z):
    for i in range(1,z+1):
        lists.append(i)
    return lists
    
fl = create_list(n)
import numpy as np 
import pandas as pd 
def sq():
    new = []
    for x in fl:
        new.append(x**2)
    return new

fpd = pd.Series(sq(), index = fl)
print(fpd)

9
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64


In [0]:
import numpy as np
a=np.arange(1,133).reshape(11,12)
print(a)
print(np.shape(a))
print(a[8,3])

[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [ 13  14  15  16  17  18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34  35  36]
 [ 37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72]
 [ 73  74  75  76  77  78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132]]
(11, 12)
100


**Missing Values Percentage**

Description

Find out the percentage of missing values in each column in the given dataset.

In [0]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
percent_missing = df.isnull().sum() * 100 / len(df)
print(round(percent_missing,2))

Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                  0.24
Discount               0.65
Order_Quantity         0.65
Profit                 0.65
Shipping_Cost          0.65
Product_Base_Margin    1.30
dtype: float64


**Mean Imputation**

Description

Impute the mean value at all the missing values of the column 'Product_Base_Margin' and then print the percentage of missing values in each column.

In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
df['Product_Base_Margin'] = df['Product_Base_Margin'].fillna((df['Product_Base_Margin'].mean()))
percent_missing = df.isnull().sum() * 100 / len(df)
print(round((percent_missing),2))

Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                  0.24
Discount               0.65
Order_Quantity         0.65
Profit                 0.65
Shipping_Cost          0.65
Product_Base_Margin    0.00
dtype: float64
